version: '3'

services:
  arangodb:
    image: arangodb/arangodb:3.6.1
    container_name: arangodb
    restart: always
    ports:
      - 8529:8529
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - /mnt/data/arango/shared:/data
      - /mnt/data/arango/backup:/backup
      - /mnt/data/arango/arangodb3:/var/lib/arangodb3
    logging:
      driver: syslog
      options:
        syslog-facility: "local1"
  patfams-redis:
      image: redis:5
      container_name: patfams-redis
      restart: always
      volumes:
          - /mnt/data/redis/data:/data
      ports:
          - "6379:6379"
      sysctls:
          net.core.somaxconn: 1024
      logging:
          driver: syslog
          options:
              syslog-facility: "local1"
